### ISSUE TITLE
When I run `agenthive/examples/train.py ` , there happens a KeyError: 'full_done_spec'

### ISSUE THREAD

**Issue by BrightMoonStar** [facebookresearch/rlhive#20]
When I run `agenthive/examples/train.py ` , there happens a KeyError: 'full_done_spec'

```
/home/dellpc/anaconda3/envs/hive/bin/python /home/dellpc/Downloads/robot/code/hive/agenthive/examples/train.py 
/home/dellpc/Downloads/robot/code/hive/agenthive/examples/train.py:9: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_name="sac_mixed.yaml", config_path="config")
/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
RoboHive:> Registering Arms Envs
RoboHive:> Registering Myo Envs
RoboHive:> Registering Hand Envs
RoboHive:> Registering Appliances Envs
RoboHive:> Registering Kitchen Envs
RoboHive:> Registering Multi-Task (2 subtasks) Envs
RoboHive:> Registering Multi-Task (9 subtasks) Envs
RoboHive:> Registering TCDM Envs
RoboHive:> Registering Claw Envs
RLHive:> Registering Franka Envs
Registered a new env-variant: visual_franka_slide_random-v3
Registered a new env-variant: visual_franka_slide_close-v3
Registered a new env-variant: visual_franka_slide_open-v3
Registered a new env-variant: visual_franka_micro_random-v3
Registered a new env-variant: visual_franka_micro_close-v3
Registered a new env-variant: visual_franka_micro_open-v3
RLHive:> Registering Kitchen Envs
Registered a new env-variant: visual_kitchen_knob1_off-v3
Registered a new env-variant: visual_kitchen_knob1_on-v3
Registered a new env-variant: visual_kitchen_knob2_off-v3
Registered a new env-variant: visual_kitchen_knob2_on-v3
Registered a new env-variant: visual_kitchen_knob3_off-v3
Registered a new env-variant: visual_kitchen_knob3_on-v3
Registered a new env-variant: visual_kitchen_knob4_off-v3
Registered a new env-variant: visual_kitchen_knob4_on-v3
Registered a new env-variant: visual_kitchen_light_off-v3
Registered a new env-variant: visual_kitchen_light_on-v3
Registered a new env-variant: visual_kitchen_sdoor_close-v3
Registered a new env-variant: visual_kitchen_sdoor_open-v3
Registered a new env-variant: visual_kitchen_ldoor_close-v3
Registered a new env-variant: visual_kitchen_ldoor_open-v3
Registered a new env-variant: visual_kitchen_rdoor_close-v3
Registered a new env-variant: visual_kitchen_rdoor_open-v3
Registered a new env-variant: visual_kitchen_micro_close-v3
Registered a new env-variant: visual_kitchen_micro_open-v3
Registered a new env-variant: visual_FK1_RelaxFixed-v4
RLHive:> Registering Arm Envs
Registered a new env-variant: visual_door-v1
Registered a new env-variant: visual_hammer-v1
Registered a new env-variant: visual_pen-v1
Registered a new env-variant: visual_relocate-v1
RLHive:> Registering Myo Envs
Registered a new env-variant: visual_motorFingerReachFixed-v0
rendering device: 0, device is cuda:0
RoboHive:> For environment credits, please cite -
    RoboHive: A unified framework for robot learning | https://sites.google.com/view/robohive
        Code: https://github.com/vikashplus/robohive/stargazers (add a star to support the project)
    
[2023-12-09 15:05:21,505][OpenGL.acceleratesupport][INFO] - No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
[2023-12-09 15:05:21,523][absl][INFO] - MUJOCO_GL=egl, attempting to import specified OpenGL backend.
[2023-12-09 15:05:21,526][absl][INFO] - MuJoCo library version is: 2.3.3
Warning: Unused kwargs found: {'frameskip': 1, 'return_dict': True}
Configuring a new session for Franka_kitchen_sim(sim)
Reading robot-configurations from /home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/robohive/envs/multi_task/substeps1/../common/slidecabinet/franka_slidecabinet.config
Configuring component franka
Configuring component slidecabinet
dict_keys(['rgb:right_cam:224x224:2d', 'rgb:left_cam:224x224:2d'])
rgb:right_cam:224x224:2d
dict_keys(['rgb:right_cam:224x224:2d', 'rgb:left_cam:224x224:2d'])
rgb:left_cam:224x224:2d
Using 224x224 visual inputs with 2d encoder
Resetting Franka_kitchen_sim(sim)
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/dellpc/Downloads/robot/code/hive/agenthive/examples/train.py", line 12, in main
    train_sac(args)
  File "/home/dellpc/Downloads/robot/code/hive/agenthive/examples/sac.py", line 284, in main
    train_env = make_env(num_envs=args.env_per_collector, task=args.task, **env_configs)
  File "/home/dellpc/Downloads/robot/code/hive/agenthive/examples/sac.py", line 104, in make_env
    base_env = RoboHiveEnv(task, device=device)
  File "/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/torchrl/envs/libs/gym.py", line 399, in __call__
    instance: GymWrapper = super().__call__(*args, **kwargs)
  File "/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/torchrl/envs/common.py", line 137, in __call__
    instance: EnvBase = super().__call__(*args, **kwargs)
  File "/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/torchrl/envs/libs/gym.py", line 957, in __init__
    super().__init__(**kwargs)
  File "/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/torchrl/envs/libs/gym.py", line 508, in __init__
    super().__init__(**kwargs)
  File "/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/torchrl/envs/common.py", line 2172, in __init__
    self._make_specs(self._env)  # writes the self._env attribute
  File "/home/dellpc/Downloads/robot/code/hive/agenthive/rlhive/rl_envs.py", line 114, in _make_specs
    rollout = self.rollout(2).get("next").exclude("done", "reward")[0]
  File "/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/torchrl/envs/common.py", line 1797, in rollout
    tensordict = self.reset()
  File "/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/torchrl/envs/common.py", line 1495, in reset
    return self._reset_proc_data(tensordict, tensordict_reset)
  File "/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/torchrl/envs/common.py", line 1498, in _reset_proc_data
    self._complete_done(self.full_done_spec, tensordict_reset)
  File "/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/torchrl/envs/common.py", line 937, in full_done_spec
    return self.output_spec["full_done_spec"]
  File "/home/dellpc/anaconda3/envs/hive/lib/python3.9/site-packages/torchrl/data/tensor_specs.py", line 3271, in __getitem__
    return self._specs[idx_unravel]
KeyError: 'full_done_spec'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Process finished with exit code 1

```

**Comment by vmoens** [comment]
See this [fix of the instructions](https://github.com/facebookresearch/agenthive/pull/22)
The stable versions should work from now on and you should be able to use the envs without issues!
